import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SessionManager from "@/components/SessionManage";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col mx-auto bg-[var(--color-soft-white)] text-[var(--color-text)]`}
      >
        <Header />
        <SessionManager />
        <Toaster position="top-right" />

        {/* QUAN TRỌNG */}
        <main className="flex-1 flex flex-col min-h-0">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
